<?php

namespace App\Models\BC20;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class BC20Data extends Model
{
    protected $table = 'customs.bc20_data';
    protected $primaryKey = 'idheader';
    protected $keyType = 'string';
    public $incrementing = false;
    public $timestamps = false;

    protected $fillable = [
        'idheader',
        'asuransi',
        'bruto',
        'biayapenambah',
        'biayapengurang',
        'cif',
        'dasarpengenaanpajak',
        'fob',
        'freight',
        'hargapenyerahan',
        'hargaperolehan',
        'jabatanttd',
        'kodelokasi',
        'kodepembayar',
        'kodetujuanpengiriman',
        'kodecarabayar',
        'kodecaradagang',
        'kodejenisekspor',
        'kodejenisimpor',
        'kodejenisnilai',
        'kodeincoterm',
        'kodevaluta',
        'kodejenistpb',
        'kodejenispengiriman',
        'kodejenisprosedur',
        'kodejenisplb',
        'kodepelbongkar',
        'kodepelmuat',
        'kodepeltujuan',
        'kodepeltransit',
        'kodepelekspor',
        'kodekantor',
        'kodekantorbongkar',
        'kodekantormuat',
        'kodekantortujuan',
        'kodekantorekspor',
        'kodekantorperiksa',
        'kotattd',
        'kodetps',
        'kodetujuantpb',
        'kodekenapajak',
        'kodekategoriekspor',
        'kodetujuanpemasukan',
        'kodetutuppu',
        'namatujuantpb',
        'namakantorpendek',
        'namakantorbongkar',
        'namakantormuat',
        'namakantortujuan',
        'namakantorekspor',
        'namakantorperiksa',
        'namakategoriekspor',
        'namalokasi',
        'namapelabuhanmuat',
        'namapelabuhantujuan',
        'namapelabuhanbongkar',
        'namapelabuhantransit',
        'namapelabuhanekspor',
        'namanegaratujuan',
        'namacarabayar',
        'namacaradagang',
        'namajenisimpor',
        'namajenisekspor',
        'namavaluta',
        'namajenistpb',
        'namatujuanpengiriman',
        'namatpswajib',
        'namattd',
        'namakenapajak',
        'netto',
        'nilaimaklon',
        'nomoraju',
        'nomorbuktibayar',
        'nomorbc11',
        'posbc11',
        'subposbc11',
        'niprekam',
        'nilaijasa',
        'nilaikurs',
        'ppnpajak',
        'ppnbmpajak',
        'tanggalbuktibayar',
        'tanggalttd',
        'tanggalbc11',
        'tanggalekspor',
        'tanggalperiksa',
        'tanggalnpppjk',
        'tanggaltiba',
        'tanggalaju',
        'tarifppnpajak',
        'tarifppnbmpajak',
        'uangmuka',
        'vd',
        'volume',
        'jaminan',
        'bankdevisa',
        'ndpbm',
    ];

    protected $casts = [
        'asuransi' => 'decimal:4',
        'bruto' => 'decimal:4',
        'biayapenambah' => 'decimal:4',
        'biayapengurang' => 'decimal:4',
        'cif' => 'decimal:4',
        'dasarpengenaanpajak' => 'decimal:4',
        'fob' => 'decimal:4',
        'freight' => 'decimal:4',
        'hargapenyerahan' => 'decimal:4',
        'hargaperolehan' => 'decimal:4',
        'netto' => 'decimal:4',
        'nilaimaklon' => 'decimal:4',
        'nilaijasa' => 'decimal:4',
        'nilaikurs' => 'decimal:4',
        'ppnpajak' => 'decimal:4',
        'ppnbmpajak' => 'decimal:4',
        'tarifppnpajak' => 'decimal:4',
        'tarifppnbmpajak' => 'decimal:4',
        'uangmuka' => 'decimal:4',
        'vd' => 'decimal:4',
        'volume' => 'decimal:4',
        'ndpbm' => 'decimal:4',
        'tanggalbuktibayar' => 'datetime',
        'tanggalttd' => 'datetime',
        'tanggalbc11' => 'datetime',
        'tanggalekspor' => 'datetime',
        'tanggalperiksa' => 'datetime',
        'tanggalnpppjk' => 'datetime',
        'tanggaltiba' => 'datetime',
        'tanggalaju' => 'datetime',
    ];

    /**
     * Get the header that owns the data.
     */
    public function header(): BelongsTo
    {
        return $this->belongsTo(BC20Header::class, 'idheader', 'idheader');
    }
}
